# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('title_de', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('body_en', models.TextField(blank=True, null=True, verbose_name='Body')),
                ('body_de', models.TextField(blank=True, null=True, verbose_name='Body')),
                ('public', models.BooleanField(default=True)),
            ],
        ),
    ]
