# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runid', models.CharField(help_text='The RunID (ie. year)', max_length=32, verbose_name='RunID')),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortid', models.IntegerField()),
                ('value', models.CharField(max_length=64, verbose_name='Short Value')),
                ('text_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Choice Text')),
                ('text_de', models.CharField(blank=True, max_length=200, null=True, verbose_name='Choice Text')),
                ('tags', models.CharField(blank=True, max_length=64, verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text=b'eg. <tt>1</tt>, <tt>2a</tt>, <tt>2b</tt>, <tt>3c</tt><br /> Number is also used for ordering questions.', max_length=8)),
                ('sort_id', models.IntegerField(blank=True, help_text=b'Questions within a questionset are sorted by sort order first, question number second', null=True)),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('text_de', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('type', models.CharField(choices=[(b'open', b'Open Answer, single line [input]'), (b'open-textfield', b'Open Answer, multi-line [textarea]'), (b'choice-yesno', b'Yes/No Choice [radio]'), (b'choice-yesnocomment', b'Yes/No Choice with optional comment [radio, input]'), (b'choice-yesnodontknow', b"Yes/No/Don't know Choice [radio]"), (b'comment', b'Comment Only'), (b'choice', b'Choice [radio]'), (b'choice-freeform', b'Choice with a freeform option [radio]'), (b'dropdown', b'Dropdown choice [select]'), (b'choice-multiple', b'Multiple-Choice, Multiple-Answers [checkbox]'), (b'choice-multiple-freeform', b'Multiple-Choice, Multiple-Answers, plus freeform [checkbox, input]'), (b'range', b'Range of numbers [select]'), (b'number', b'Number [input]'), (b'timeperiod', b'Time Period [input, select]'), (b'custom', b'Custom field'), (b'sameas', b'Same as Another Question (put sameas=question.number in checks or sameasid=question.id)')], help_text="Determines the means of answering the question. An open question gives the user a single-line textfield, multiple-choice gives the user a number of choices he/she can choose from. If a question is multiple-choice, enter the choices this user can choose from below'.", max_length=32, verbose_name='Type of question')),
                ('extra_en', models.CharField(blank=True, help_text='Extra information (use  on question type)', max_length=512, null=True, verbose_name='Extra information')),
                ('extra_de', models.CharField(blank=True, help_text='Extra information (use  on question type)', max_length=512, null=True, verbose_name='Extra information')),
                ('checks', models.CharField(blank=True, help_text=b'Additional checks to be performed for this value (space separated)  <br /><br />For text fields, <tt>required</tt> is a valid check.<br />For yes/no choice, <tt>required</tt>, <tt>required-yes</tt>, and <tt>required-no</tt> are valid.<br /><br />If this question is required only if another question\'s answer is something specific, use <tt>requiredif="QuestionNumber,Value"</tt> or <tt>requiredif="QuestionNumber,!Value"</tt> for anything but a specific value.  You may also combine tests appearing in <tt>requiredif</tt> by joining them with the words <tt>and</tt> or <tt>or</tt>, eg. <tt>requiredif="Q1,A or Q2,B"</tt>', max_length=512, null=True, verbose_name='Additional checks')),
                ('footer_en', models.TextField(blank=True, help_text=b'Footer rendered below the question interpreted as textile', null=True, verbose_name='Footer')),
                ('footer_de', models.TextField(blank=True, help_text=b'Footer rendered below the question interpreted as textile', null=True, verbose_name='Footer')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('redirect_url', models.CharField(default=b'/static/complete.html', help_text=b'URL to redirect to when Questionnaire is complete. Macros: $SUBJECTID, $RUNID, $LANG', max_length=128)),
            ],
            options={
                'permissions': (('export', 'Can export questionnaire answers'), ('management', 'Management Tools')),
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortid', models.IntegerField()),
                ('heading', models.CharField(max_length=64)),
                ('checks', models.CharField(blank=True, help_text=b'Current options are \'femaleonly\' or \'maleonly\' and shownif="QuestionNumber,Answer" which takes the same format as <tt>requiredif</tt> for questions.', max_length=256)),
                ('text_en', models.TextField(blank=True, help_text=b"This is interpreted as Textile: <a href='http://en.wikipedia.org/wiki/Textile_%28markup_language%29' target='_blank'>http://en.wikipedia.org/wiki/Textile_(markup_language)</a>", null=True, verbose_name='Text')),
                ('text_de', models.TextField(blank=True, help_text=b"This is interpreted as Textile: <a href='http://en.wikipedia.org/wiki/Textile_%28markup_language%29' target='_blank'>http://en.wikipedia.org/wiki/Textile_(markup_language)</a>", null=True, verbose_name='Text')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='RunInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random', models.CharField(max_length=32)),
                ('runid', models.CharField(max_length=32)),
                ('emailcount', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('emailsent', models.DateTimeField(blank=True, null=True)),
                ('lastemailerror', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(blank=True, max_length=16, null=True)),
                ('cookies', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, help_text='Tags active on this run, separated by commas')),
                ('skipped', models.TextField(blank=True, help_text='A comma sepearted list of questions to skip')),
                ('questionset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.QuestionSet')),
            ],
            options={
                'verbose_name_plural': 'Run Info',
            },
        ),
        migrations.CreateModel(
            name='RunInfoHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runid', models.CharField(max_length=32)),
                ('completed', models.DateField()),
                ('tags', models.TextField(blank=True, help_text='Tags used on this run, separated by commas')),
                ('skipped', models.TextField(blank=True, help_text='A comma sepearted list of questions skipped by this run')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questionnaire')),
            ],
            options={
                'verbose_name_plural': 'Run Info History',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[(b'active', 'Active'), (b'inactive', 'Inactive')], default=b'inactive', max_length=16, verbose_name='State')),
                ('surname', models.CharField(blank=True, max_length=64, null=True, verbose_name='Surname')),
                ('givenname', models.CharField(blank=True, max_length=64, null=True, verbose_name='Given name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('gender', models.CharField(blank=True, choices=[(b'unset', 'Unset'), (b'male', 'Male'), (b'female', 'Female')], default=b'unset', max_length=8, verbose_name='Gender')),
                ('nextrun', models.DateField(blank=True, null=True, verbose_name='Next Run')),
                ('formtype', models.CharField(choices=[(b'email', 'Subject receives emails'), (b'paperform', 'Subject is sent paper form')], default=b'email', max_length=16, verbose_name='Form Type')),
                ('language', models.CharField(choices=[(b'en', b'English'), (b'de', b'Deutsch')], default=b'en-us', max_length=2, verbose_name='Language')),
            ],
        ),
        migrations.AddField(
            model_name='runinfohistory',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Subject'),
        ),
        migrations.AddField(
            model_name='runinfo',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='questionset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.QuestionSet'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(help_text='The question that this is an answer to', on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='subject',
            field=models.ForeignKey(help_text='The user who supplied this answer', on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Subject'),
        ),
    ]
